### ISSUE TITLE
secureTextEntry not working

### ISSUE THREAD

**Issue by lpasquini** [mattermost/react-native-paste-input#9]
secureTextEntry prop does not work, tested in example on iOS and Android

**Comment by enahum** [comment]
Hi @lpasquini 

I'm wondering what would be the use case here? As the main purpose of thid input field is to allow pasting files

**Comment by lpasquini** [comment]
Hi @enahum 
In my case I need it to prevent the pasting of text, not files

**Comment by enahum** [comment]
interesting.. a quick glance into the code shows that the `TextInputProps` should be pass down as is, not entirely sure why is not working as expected. I'll try and determine what may be causing it but if you can check it out as well that'll be super helpful

**Comment by enahum** [comment]
so I've looked into this, and we inherit the Text input from ReactTextEdit for multi-line so the [secureTextEntry](https://reactnative.dev/docs/next/textinput#securetextentry) does not work in that scenario. I guess it'll be required for the change to land in React Native itself in order to support this.

**Comment by igperez-ar** [comment]
@enahum Is there no way to support multi-line and secureTextEntry at the same time? If so, how could it be modified at least with patch-package to support secureTextEntry? I don't have much knowledge of native code and even less of the library implementation. Any help is appreciated

**Comment by enahum** [comment]
> @enahum Is there no way to support multi-line and secureTextEntry at the same time? If so, how could it be modified at least with patch-package to support secureTextEntry? I don't have much knowledge of native code and even less of the library implementation. Any help is appreciated

@igperez-ar I'm afraid this is a limitation of RN https://reactnative.dev/docs/textinput#securetextentry

> secureTextEntry
If true, the text input obscures the text entered so that sensitive text like passwords stay secure. The default value is false. Does not work with multiline={true}.

This component is built as an extension of RN TextInput component

**Comment by igperez-ar** [comment]
I understand, but the problem is that the `secureTextEntry` property does not work on this input despite not using `multiline={true}`. At least on iOS in my case

**Comment by enahum** [comment]
Yes cause this inpur is based on multiline regardless.. in RN under the hood multiline and single line are in two different native components I believe

**Comment by igperez-ar** [comment]
So just changing the imports from `#import <React/RCTMultilineTextInputViewManager.h>` to `#import <React/RCTSinglelineTextInputViewManager.h>` should be enough to support that property? Because I don't need multiline but need SecureTextEntry support
